### PR TITLE
Update route to use new location of thumbnails

### PR DESCRIPTION
**Pull request by Nerodacles**

### CODE REVIEW

**Comment by Nerodacles** [comment]
I was trying to lint, but always got error, so i cried myself to sleep. But now people "faces" show up!

**Comment by derneuere** [comment]
Looks good to me, but please squash the commits 😊

**Comment by derneuere** [comment]
Not sure if you know how to do this, so I looked up a tutorial: https://getaround.tech/git-rebase-edit-history/

**Comment by Nerodacles** [comment]
Ok, trying it now!

**Comment by Nerodacles** [comment]
Thanks a lot!!

**Comment by derneuere** [comment]
Awesome! 👍

**Pull request merged**
